"""payments constants"""
from decouple import config

ACTIVE_GIFT_CARD_STATE = "ACTIVE"
PENDING_GIFT_CARD_STATE = "PENDING"

LOAD_GIFT_CARD = "LOAD"
ACTIVATE_GIFT_CARD = "ACTIVATE"

GIFT_CARD = "gift_card"

GIFT_CARD_STATE_TYPES = [PENDING_GIFT_CARD_STATE, ACTIVE_GIFT_CARD_STATE]

LOCATION_ID = config("DJANGO_PAYMENT_LOCATION_ID")

MAX_BALANCE_IN_WALLET = 750

DEFAULT_PAYMENT_METHOD_AS_WALLET = -1
DEFAULT_PAYMENT_METHOD_AS_PAY_AS_YOU_GO = -2
