# Generated by Django 3.2.11 on 2022-05-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingsession',
            name='is_force_stopped',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='deleted',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='is_shop_wise',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='timed_expiry',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltyavailableon',
            name='deleted',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True),
        )
    ]
