# Generated by Django 3.2.11 on 2022-05-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0002_auto_20220506_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfguserev',
            name='user_email',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
