# Generated by Django 3.2.11 on 2022-05-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0003_mfguserev_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='verify_email',
            field=models.CharField(blank=True, max_length=1000),
        )
    ]
