# Generated by Django 3.2.11 on 2022-05-26 13:16

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0004_emailverification_verify_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconfigurations',
            name='base_configuration_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baseconfigurations',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='is_reviewed',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('App', 'App')], default='App', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SessionTransactionStatusTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, choices=[('Successful', 'Successful'), ('Failed', 'Failed')], default='Successful', max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, to='sharedServices.adminuser')),
                ('session_id', models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, to='sharedServices.chargingsession')),
            ],
        ),
        migrations.AlterField(
            model_name='sessiontransactionstatustracker',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
