# Generated by Django 3.2.11 on 2022-07-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0005_base_conf_migratins'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfiguration',
            name='image_path_without_text',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
