# Generated by Django 3.2.11 on 2022-07-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0006_serviceconfiguration_image_path_without_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceconfiguration',
            old_name='image_path_without_text',
            new_name='image_path_with_text',
        ),
    ]
