# Generated by Django 3.2.11 on 2022-07-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0007_rename_image_path_without_text_serviceconfiguration_image_path_with_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricvehicledatabase',
            name='ev_thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnail/'),
        ),
    ]
