# Generated by Django 3.2.11 on 2022-07-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0008_electricvehicledatabase_ev_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_gift_card_gan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_gift_card_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chargepoint',
            name='payter_terminal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectorconfiguration',
            name='sorting_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_payment_method',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='baseconfigurations',
            name='base_configuration_value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
