# Generated by Django 3.2.11 on 2022-07-20 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0009_auto_20220720_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_customer_id', models.CharField(max_length=1000, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_for_type', models.CharField(blank=True, choices=[('Wallet', 'Wallet'), ('Loyalty', 'Loyalty')], default='', max_length=100, null=True)),
                ('payment_for_subtype', models.CharField(blank=True, choices=[('Load', 'Load'), ('Activate', 'Activate')], default='', max_length=100, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], default='', max_length=100, null=True)),
                ('payment_response', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference_id', models.IntegerField(default=0)),
                ('reference_current_status', models.CharField(blank=True, choices=[('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], default='', max_length=100, null=True)),
                ('reference_response', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_reviewed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
