# Generated by Django 3.2.11 on 2022-07-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0010_transactionstracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionstracker',
            name='payment_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionstracker',
            name='reference_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
