# Generated by Django 3.2.11 on 2022-07-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0011_auto_20220720_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstracker',
            name='refund_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactionstracker',
            name='refund_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionstracker',
            name='refund_initiated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionstracker',
            name='refund_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionstracker',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Pending', 'Pending'), ('Completed', 'Completed')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactionstracker',
            name='transaction_amount',
            field=models.IntegerField(default=0),
        ),
    ]
