# Generated by Django 3.2.11 on 2022-07-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0012_auto_20220722_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionstracker',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default=None, max_length=100, null=True),
        ),
    ]
