# Generated by Django 3.2.11 on 2022-07-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0013_alter_transactionstracker_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstracker',
            name='refund_reference_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
