# Generated by Django 3.2.11 on 2022-07-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0014_transactionstracker_refund_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionstracker',
            name='payment_for_subtype',
            field=models.CharField(blank=True, choices=[('Load', 'Load'), ('Activate', 'Activate'), ('Redeem', 'Redeem')], default='', max_length=100, null=True),
        ),
    ]
