# Generated by Django 3.2.11 on 2022-09-21 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0015_alter_transactionstracker_payment_for_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactlessReceiptEmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True)),
                ('session_id', models.CharField(max_length=100, null=True)),
                ('emails_sent_count', models.IntegerField(default=0)),
                ('log_created_date', models.DateTimeField(blank=True, null=True)),
                ('log_updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transactionstracker',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharedServices.mfguserev'),
        ),
    ]
