# Generated by Django 3.2.11 on 2022-09-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0016_auto_20220921_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactlessreceiptemailtracking',
            old_name='log_created_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='contactlessreceiptemailtracking',
            old_name='log_updated_date',
            new_name='updated_date',
        ),
        migrations.RemoveField(
            model_name='contactlessreceiptemailtracking',
            name='emails_sent_count',
        ),
    ]
