# Generated by Django 3.2.11 on 2022-10-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0017_auto_20220921_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount_due',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='amount_due_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
