# Generated by Django 3.2.11 on 2022-10-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0018_auto_20221004_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='amount_due_session_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='due_amount_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='have_amount_due',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True),
        ),
    ]
