# Generated by Django 3.2.11 on 2022-10-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0019_auto_20221007_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audittrail',
            old_name='data_id',
            new_name='data_db_id',
        ),
        migrations.AddField(
            model_name='audittrail',
            name='module_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='user_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='user_role',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='review_status',
            field=models.CharField(blank=True, default='No', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactionstracker',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharedServices.adminuser'),
        ),
    ]
