# Generated by Django 3.2.11 on 2022-11-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0020_auto_20221014_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='changes_reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baseconfigurations',
            name='add_to_cache',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baseconfigurations',
            name='frequently_used',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wallet_balance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactionstracker',
            name='driivz_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
