# Generated by Django 3.2.11 on 2022-12-10 11:29

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0020_auto_20221014_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='images')),
                ('deleted', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_to', models.CharField(blank=True, choices=[('All App Users', 'All App Users'), ('Only Subscribed Users', 'Only Subscribed Users')], max_length=60, null=True)),
                ('subject', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('template', models.CharField(blank=True, choices=[('Pre-release', 'Pre-release'), ('Post-release', 'Post-release'), ('Custom', 'Custom')], max_length=60, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Delivered', 'Delivered'), ('Scheduled', 'Scheduled')], max_length=60, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('deleted', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('email_attachments', models.ManyToManyField(to='sharedServices.EmailAttachments')),
            ],
        ),
    ]
