# Generated by Django 3.2.11 on 2022-11-23 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0021_audittrail_changes_reference_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactlessSessionsDownloadedReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('driivz_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payter_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_data', models.TextField(blank=True, null=True)),
                ('downloaded_date', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_charging_sessions_receipts', related_query_name='user_charging_sessions_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contactless_downloaded_receipts',
            },
        ),
        migrations.AlterField(
            model_name='transactionstracker',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
