# Generated by Django 3.2.11 on 2022-12-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0022_contactlesssessionsdownloadedreceipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfguserev',
            name='phone_number',
            field=models.BinaryField(blank=True, max_length='max', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor_done',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactlesssessionsdownloadedreceipts',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_charging_sessions_receipts', related_query_name='user_charging_sessions_receipts', to='sharedServices.mfguserev'),
        ),
    ]
