# Generated by Django 3.2.11 on 2022-12-01 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0023_auto_20221202_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstracker',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionstracker',
            name='user_updated_balance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactlesssessionsdownloadedreceipts',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_charging_sessions_receipts', related_query_name='user_charging_sessions_receipts', to='sharedServices.mfguserev'),
        ),
    ]
