# Generated by Django 3.2.11 on 2022-12-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0024_auto_20221201_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstracker',
            name='is_withdrawn',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactionstracker',
            name='processed_by',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('App', 'App')], default='', max_length=100, null=True),
        ),
    ]
