# Generated by Django 3.2.11 on 2022-12-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0025_auto_20221201_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionstracker',
            name='is_withdrawn',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionstracker',
            name='processed_by',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('App', 'App')], default='App', max_length=100, null=True),
        ),
    ]
