# Generated by Django 3.2.11 on 2022-12-08 13:54

from django.db import migrations, models
import sharedServices.model_files.station_models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0026_auto_20221201_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='payment_method',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stationconnector',
            name='connector_sorting_order',
            field=models.CharField(default='', max_length=30, validators=[sharedServices.model_files.station_models.validate_min_length]),
        ),
    ]
