# Generated by Django 3.2.11 on 2022-12-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0027_auto_20221208_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlesssessionsdownloadedreceipts',
            name='session_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactlesssessionsdownloadedreceipts',
            name='session_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactlesssessionsdownloadedreceipts',
            name='session_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactlesssessionsdownloadedreceipts',
            name='session_power_consumed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
