# Generated by Django 3.2.11 on 2022-12-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0028_auto_20221210_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unsubscribed_from_emails',
            field=models.CharField(blank=True, default='No', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
