# Generated by Django 3.2.11 on 2022-12-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0029_auto_20221210_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionstracker',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
