# Generated by Django 3.2.11 on 2022-12-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0021_emailattachments_emailnotifications'),
        ('sharedServices', '0030_alter_transactionstracker_payment_id'),
    ]

    operations = [
    ]
