# Generated by Django 3.2.11 on 2023-04-04 07:37

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0031_merge_20221221_1506"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushNotifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assign_to",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "regions",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "screens",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "category",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "push_notification",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "inapp_notification",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="img/logo-black.png",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "delivered_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "deleted",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "updated_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chargingsession",
            name="preauth_collected_by",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chargingsession",
            name="preauth_status",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="emailattachments",
            name="attachment_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailnotifications",
            name="email_preference",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_marketing_update_preference_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_news_letter_preference_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_promotion_preference_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="fcm_device_token",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="inapp_notification_object",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="loyalty_preference_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="other_preference_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="promotion_preference_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transactions",
            name="payment_for",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transactions",
            name="payment_for_reference_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="audittrail",
            name="module_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="emailnotifications",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
