# Generated by Django 3.2.11 on 2023-04-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0032_auto_20230404_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unsubscribed_from_emails',
        ),
    ]
