# Generated by Django 3.2.11 on 2023-04-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0034_remove_profile_unsubscribed_from_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotifications',
            name='user_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
