# Generated by Django 3.2.11 on 2023-06-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharedServices", "0035_emailnotifications_user_list"),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyServicesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('data', models.TextField(null=True)),
                ('status', models.CharField(blank=True, choices=[('Complete', 'Complete'), ('Inprogress', 'Inprogress'), ('Failed', 'Failed')], default='Inprogress', max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'thirdparty_services_data',
            },
        ),
        migrations.AddField(
            model_name="chargingsession",
            name="session_tariff",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="user_domain",
            field=models.CharField(default="normal_user", max_length=100),
        ),
        migrations.AddField(
            model_name="pushnotifications",
            name="domain",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="stations",
            name="site_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
