# Generated by Django 4.1.7 on 2023-06-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharedServices", "0036_auto_20230609_1711"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingsession",
            name="payment_type",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
