# Generated by Django 3.2.11 on 2023-07-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0037_chargingsession_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotifications',
            name='postcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_ev_updates_preference_status',
            field=models.BooleanField(default=True),
        ),
    ]
