# Generated by Django 3.2.11 on 2023-08-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0038_auto_20230724_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltytransactions',
            name='count_of_transactions',
            field=models.IntegerField(default=1),
        ),
    ]
