# Generated by Django 3.2.11 on 2023-09-07 08:04

from django.db import migrations, models
import django.db.models.deletion
import sharedServices.model_files.station_models


class Migration(migrations.Migration):
    dependencies = [
        ("sharedServices", "0039_loyaltytransactions_count_of_transactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingsession",
            name="deducted_voucher_amount",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactlessreceiptemailtracking',
            name='source',
            field=models.CharField(default='driivz and payter', max_length=100),
        ),
        migrations.AddField(
            model_name="stations",
            name="valeting",
            field=models.CharField(
                blank=True, default="No", max_length=30, null=True
            ),
        ),
        migrations.CreateModel(
            name="ValetingTerminals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="",
                        max_length=30,
                        validators=[
                            sharedServices.model_files.station_models.validate_min_length
                        ],
                    ),
                ),
                (
                    "payter_serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "amenities",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[
                            sharedServices.model_files.station_models.validate_min_length
                        ],
                    ),
                ),
                (
                    "deleted",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        max_length=100,
                    ),
                ),
                (
                    "station_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sharedServices.stations",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaidPaymentLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.CharField(max_length=1000, null=True)),
                (
                    "paid_due_amount",
                    models.CharField(max_length=100, null=True),
                ),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "charging_session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sharedServices.chargingsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sharedServices.mfguserev",
                    ),
                ),
            ],
        ),
    ]
