# Generated by Django 3.2.11 on 2023-09-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0040_auto_20230907_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotifications',
            name='regions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
