# Generated by Django 3.2.11 on 2023-11-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0041_alter_pushnotifications_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='payment_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
