# Generated by Django 3.2.11 on 2023-11-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0042_transactions_payment_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='loyalty_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='loyalty',
            name='number_of_total_issuances',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyalty',
            name='reward_expiration_notification_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_expiration_notifications', related_query_name='reward_expiration_notifications', to='sharedServices.pushnotifications'),
        ),
        migrations.AddField(
            model_name='loyalty',
            name='reward_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='loyalty',
            name='reward_unlocked_notification_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_unlocked_notifications', related_query_name='reward_unlocked_notifications', to='sharedServices.pushnotifications'),
        ),
        migrations.AddField(
            model_name='loyalty',
            name='voucher_issuance_trigger_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
