# Generated by Django 3.2.11 on 2023-11-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0043_auto_20231127_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='expire_reward_before_x_number_of_days',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='loyalty',
            name='reward_activated_notification_expiry',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='loyalty',
            name='reward_expiration_notification_expiry',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
