# Generated by Django 3.2.11 on 2023-12-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0044_auto_20231129_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='reward_expiry_notification_trigger_time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
