# Generated by Django 3.2.11 on 2023-12-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0045_loyalty_reward_expiry_notification_trigger_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyalty',
            name='reward_expiry_notification_trigger_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
