# Generated by Django 3.2.11 on 2023-12-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0047_alter_loyalty_reward_expiry_notification_trigger_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotifications',
            name='notification_for',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pushnotifications',
            name='assign_to',
            field=models.TextField(blank=True, null=True),
        ),
    ]
