# Generated by Django 3.2.11 on 2023-12-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0048_auto_20231206_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyalty',
            name='voucher_issuance_trigger_value',
        ),
    ]
