# Generated by Django 3.2.11 on 2023-12-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0049_remove_loyalty_voucher_issuance_trigger_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='number_of_issued_vouchers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userloyaltytransactions',
            name='action_code',
            field=models.CharField(blank=True, choices=[('Purchased', 'Purchased'), ('Redeemed', 'Redeemed'), ('Burned', 'Burned')], max_length=60, null=True),
        ),
    ]
