# Generated by Django 3.2.11 on 2023-12-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0050_auto_20231206_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='station_loyalty_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
