# Generated by Django 3.2.11 on 2023-12-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0051_loyalty_station_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyalty',
            name='number_of_paid_purchases',
            field=models.FloatField(default=0),
        ),
    ]
