# Generated by Django 3.2.11 on 2024-01-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0052_alter_loyalty_number_of_paid_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyalty',
            name='offer_details',
            field=models.CharField(blank=True, max_length=1100, null=True),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='terms_and_conditions',
            field=models.CharField(blank=True, max_length=1100, null=True),
        ),
    ]
