# Generated by Django 3.2.11 on 2024-01-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0053_auto_20240110_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='payment_terminal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stations',
            name='receipt_hero_site_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
