# Generated by Django 3.2.11 on 2024-02-15 11:22

from django.db import migrations, models
import sharedServices.model_files.station_models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0054_stations_payment_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='station_id',
            field=models.CharField(default='', max_length=15, unique=True, validators=[sharedServices.model_files.station_models.validate_min_length]),
        ),
    ]
