# Generated by Django 3.2.11 on 2024-02-21 10:18

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0055_alter_stations_station_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactlesssessionsdownloadedreceipts',
            old_name='payter_transaction_id',
            new_name='payter_or_rh_transaction_id',
        ),
        migrations.AlterField(
            model_name='baseconfigurations',
            name='base_configuration_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
