# Generated by Django 3.2.11 on 2024-03-07 10:26

from django.db import migrations, models
import sharedServices.model_files.station_models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0056_rename_payter_transaction_id_contactlesssessionsdownloadedreceipts_payter_or_rh_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyavailableon',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltyavailableon',
            name='operation_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltyavailableon',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltyavailableon',
            name='station_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promotionsavailableon',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='promotionsavailableon',
            name='operation_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='promotionsavailableon',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='station_name',
            field=models.CharField(default='', max_length=200, validators=[sharedServices.model_files.station_models.validate_min_length]),
        ),
    ]
