# Generated by Django 3.2.11 on 2024-06-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0057_auto_20240307_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='loyalty_list_footer_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
