# Generated by Django 3.2.11 on 2024-06-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0059_alter_stations_payment_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfguserev',
            name='phone_number_v2',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
