# Generated by Django 3.2.11 on 2024-06-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0058_loyalty_loyalty_list_footer_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='payment_terminal',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
