# Generated by Django 3.2.11 on 2024-06-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0059_mfguserev_phone_number_v2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mfguserev',
            old_name='phone_number_v2',
            new_name='hashed_phone_number',
        ),
    ]
