# Generated by Django 3.2.11 on 2024-06-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0060_rename_phone_number_v2_mfguserev_hashed_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfguserev',
            name='hashed_phone_number',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
    ]
