# Generated by Django 3.2.11 on 2024-07-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0061_alter_mfguserev_hashed_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptHeroReceiptsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100, null=True)),
                ('rh_data', models.TextField(null=True)),
                ('driivz_data', models.TextField(null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'receiptHero_receipts_data',
            },
        ),
    ]
