# Generated by Django 3.2.11 on 2025-02-04 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0062_receiptheroreceiptsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriivzData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=75, null=True, unique=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'driivz_data',
            },
        ),
        migrations.AddField(
            model_name='baseconfigurations',
            name='for_app_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receiptheroreceiptsdata',
            name='transaction_id',
            field=models.CharField(default=str(datetime.datetime.now()), max_length=100),
        ),
        migrations.AddField(
            model_name='stations',
            name='driivz_display_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
