# Generated by Django 5.0.9 on 2025-04-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0063_auto_20250204_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptheroreceiptsdata',
            name='transaction_id',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ValetingTransactionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('card_number', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valeting_site_id', models.CharField(max_length=100)),
                ('data', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'valeting_transaction_data',
                'indexes': [models.Index(fields=['transaction_id', 'card_number'], name='valeting_tr_transac_ac3c3b_idx')],
            },
        ),
    ]
