# Generated by Django 5.0.9 on 2024-10-23 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0063_auto_20250204_1838"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUserSignInLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sign_in_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Google Sign In", "Google Sign In"),
                            ("Apple Sign In", "Apple Sign In"),
                            ("Email Sign In", "Email Sign In"),
                        ],
                        max_length=1000,
                        null=True,
                    ),
                ),
                ("login_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_sign_in_logs",
                        related_query_name="user_sign_in_logs",
                        to="sharedServices.mfguserev",
                    ),
                ),
            ],
        ),
    ]
