# Generated by Django 5.0.9 on 2025-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0064_alter_receiptheroreceiptsdata_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valetingtransactiondata',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valetingtransactiondata',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valetingtransactiondata',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='valetingtransactiondata',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
