# Generated by Django 5.0.9 on 2025-04-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0065_alter_valetingtransactiondata_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='valeting_site_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
