# Generated by Django 5.0.9 on 2024-10-28 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0066_appuserthirdpartyregistrationfailedapilogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appusersigninlogs",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_sign_in_logs",
                related_query_name="user_sign_in_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
