# Generated by Django 5.0.9 on 2024-11-12 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0068_userselectedstationfinderfilters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuserthirdpartyregistrationfailedapilogs",
            name="user",
        ),
        migrations.AddField(
            model_name="appuserthirdpartyregistrationfailedapilogs",
            name="app_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="third_party_failed_api_log",
                related_query_name="third_party_failed_api_log",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
