# Generated by Django 5.0.9 on 2024-11-14 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sharedServices",
            "0069_remove_appuserthirdpartyregistrationfailedapilogs_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="baseconfigurations",
            name="for_app_version",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="connectorconfiguration",
            name="for_app_version",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="appusersigninlogs",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_sign_in_logs",
                related_query_name="user_sign_in_logs",
                to="sharedServices.mfguserev",
            ),
        ),
        migrations.AlterField(
            model_name="appuserthirdpartyregistrationfailedapilogs",
            name="app_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="third_party_failed_api_log",
                related_query_name="third_party_failed_api_log",
                to="sharedServices.mfguserev",
            ),
        ),
        migrations.AlterField(
            model_name="userselectedstationfinderfilters",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_selected_station_finder_filters",
                related_query_name="user_selected_station_finder_filters",
                to="sharedServices.mfguserev",
            ),
        ),
    ]
