# Generated by Django 5.0.9 on 2024-11-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0070_baseconfigurations_for_app_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargepoint",
            name="ev_charge_point_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="stations",
            name="ev_station_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
