# Generated by Django 5.0.9 on 2024-11-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0071_chargepoint_ev_charge_point_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectorconfiguration",
            name="alternate_image_path",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
