# Generated by Django 5.0.9 on 2024-11-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0072_connectorconfiguration_alternate_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingsession",
            name="charging_authorization_status",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="chargingsession",
            name="is_refund_initiated",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=100,
                null=True,
            ),
        ),
    ]
