# Generated by Django 5.0.9 on 2024-11-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sharedServices",
            "0073_chargingsession_charging_authorization_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingsession",
            name="user_card_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
