# Generated by Django 5.0.9 on 2024-11-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0074_chargingsession_user_card_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingsession",
            name="is_refund_initiated",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No"), ("Completed", "Completed")],
                default="No",
                max_length=100,
                null=True,
            ),
        ),
    ]
