# Generated by Django 5.0.9 on 2024-11-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0075_alter_chargingsession_is_refund_initiated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingsession",
            name="is_refund_initiated",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chargingsession",
            name="paid_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paid", "paid"),
                    ("unpaid", "unpaid"),
                    ("refunded", "refunded"),
                ],
                default="unpaid",
                max_length=100,
            ),
        ),
    ]
