# Generated by Django 5.0.9 on 2024-11-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0076_alter_chargingsession_is_refund_initiated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargepoint",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
