# Generated by Django 5.0.9 on 2024-12-05 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0077_chargepoint_manufacturer"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEVs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default", models.BooleanField(default=False, null=True)),
                (
                    "vehicle_registration_number",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "vehicle_nickname",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ev_users",
                        related_query_name="ev_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_evs",
                        related_query_name="user_evs",
                        to="sharedServices.electricvehicledatabase",
                    ),
                ),
            ],
        ),
    ]
