# Generated by Django 5.0.9 on 2024-12-09 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0078_userevs"),
    ]

    operations = [
        migrations.AddField(
            model_name="mfguserev",
            name="sign_in_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Google Sign In", "Google Sign In"),
                    ("Apple Sign In", "Apple Sign In"),
                    ("Email Sign In", "Email Sign In"),
                ],
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userevs",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ev_users",
                related_query_name="ev_users",
                to="sharedServices.mfguserev",
            ),
        ),
        migrations.DeleteModel(
            name="AppUserSignInLogs",
        ),
    ]
