# Generated by Django 5.0.9 on 2024-12-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sharedServices",
            "0079_mfguserev_sign_in_method_alter_userevs_user_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chargingsession",
            name="user_card_id",
        ),
        migrations.AddField(
            model_name="chargingsession",
            name="user_card_number",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
