# Generated by Django 5.0.9 on 2024-12-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0080_remove_chargingsession_user_card_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapmarkerconfigurations",
            name="small_map_marker_image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
