# Generated by Django 5.0.9 on 2024-12-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0081_mapmarkerconfigurations_small_map_marker_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_3ds_check_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="user_specific_3ds_configurations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="user_specific_3ds_set_by_admin",
            field=models.BooleanField(default=True),
        ),
    ]
