# Generated by Django 5.0.9 on 2024-12-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0082_profile_is_3ds_check_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_specific_3ds_configurations_updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
