# Generated by Django 5.0.9 on 2024-12-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0083_profile_user_specific_3ds_configurations_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="is_3ds_check_active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_specific_3ds_set_by_admin",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
