# Generated by Django 5.0.9 on 2024-12-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0084_alter_profile_is_3ds_check_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_specific_3ds_configurations",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_specific_3ds_set_by_admin",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
