# Generated by Django 5.0.9 on 2024-12-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sharedServices",
            "0085_alter_profile_user_specific_3ds_configurations_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="number_of_transactions_for_3ds_check",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_3ds_check_active",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
