# Generated by Django 5.0.9 on 2024-12-24 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sharedServices",
            "0086_profile_number_of_transactions_for_3ds_check_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreeDSTriggerLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_for_3ds",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reason_for_3ds_kwh",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reason_for_3ds_days",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reason_for_3ds_transactions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "configuration_set_by_admin_for_3ds",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "configuration_set_by_admin_for_3ds_kwh",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "configuration_set_by_admin_for_3ds_days",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "configuration_set_by_admin_for_3ds_transactions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_3ds_trigger_logs",
                        related_query_name="user_3ds_trigger_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThreeDSCheckLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("Successful", "Successful"), ("Failed", "Failed")],
                        default="Successful",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                (
                    "session_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_3ds_check_logs",
                        related_query_name="user_3ds_check_logs",
                        to="sharedServices.chargingsession",
                    ),
                ),
                (
                    "three_ds_treigger_log_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sharedServices.threedstriggerlogs",
                    ),
                ),
            ],
        ),
    ]
