# Generated by Django 5.0.9 on 2024-12-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0087_threedstriggerlogs_threedschecklogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="threedstriggerlogs",
            name="remaining_3ds_check_transaction",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
