# Generated by Django 5.0.9 on 2024-12-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0088_threedstriggerlogs_remaining_3ds_check_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="number_of_transactions_for_3ds_check",
        ),
    ]
