# Generated by Django 5.0.9 on 2024-12-24 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0089_remove_profile_number_of_transactions_for_3ds_check"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="threedschecklogs",
            name="three_ds_treigger_log_id",
        ),
        migrations.AddField(
            model_name="threedschecklogs",
            name="three_ds_trigger_log_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sharedServices.threedstriggerlogs",
            ),
        ),
        migrations.AddField(
            model_name="threedstriggerlogs",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Triggered", "Triggered"),
                    ("Running", "Running"),
                    ("Completed", "Completed"),
                ],
                default="Triggered",
                max_length=100,
                null=True,
            ),
        ),
    ]
