# Generated by Django 5.0.9 on 2025-01-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sharedServices",
            "0090_remove_threedschecklogs_three_ds_treigger_log_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stations",
            name="overstay_fee",
            field=models.FloatField(default=0, null=True),
        ),
    ]
