# Generated by Django 5.0.9 on 2025-01-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0091_stations_overstay_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="threedstriggerlogs",
            name="updated_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
