# Generated by Django 5.0.9 on 2025-01-13 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0092_threedstriggerlogs_updated_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threedschecklogs",
            name="session_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_3ds_check_logs",
                related_query_name="user_3ds_check_logs",
                to="sharedServices.chargingsession",
            ),
        ),
    ]
