# Generated by Django 5.0.9 on 2025-02-04 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0093_alter_threedschecklogs_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="loyalty",
            name="daily_offer_from_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loyalty",
            name="daily_offer_till_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loyalty",
            name="offer_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Generic Offers", "Generic Offers"),
                    ("Loyalty Offers", "Loyalty Offers"),
                    ("Daily Offers", "Daily Offers"),
                ],
                max_length=60,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loyalty",
            name="show_daily_offer",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="threedstriggerlogs",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_3ds_trigger_logs",
                related_query_name="user_3ds_trigger_logs",
                to="sharedServices.mfguserev",
            ),
        ),
    ]
