# Generated by Django 5.0.9 on 2025-02-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharedServices", "0094_loyalty_daily_offer_from_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactlesssessionsdownloadedreceipts",
            name="is_version_4_receipt",
            field=models.BooleanField(default=False),
        ),
    ]
