# Generated by Django 5.0.9 on 2025-03-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sharedServices",
            "0095_contactlesssessionsdownloadedreceipts_is_version_4_receipt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="loyalty",
            name="occurance_status",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loyalty",
            name="steps_to_redeem",
            field=models.CharField(blank=True, max_length=1100, null=True),
        ),
        migrations.AlterField(
            model_name="loyalty",
            name="offer_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Generic Offers", "Generic Offers"),
                    ("Loyalty Offers", "Loyalty Offers"),
                ],
                max_length=60,
                null=True,
            ),
        )
    ]
