# Generated by Django 5.0.9 on 2025-03-01 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sharedServices",
            "0096_loyalty_occurance_status_loyalty_steps_to_redeem_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="loyalty",
            old_name="show_daily_offer",
            new_name="show_occurrence_offer",
        ),
        migrations.RemoveField(
            model_name="loyalty",
            name="daily_offer_from_time",
        ),
        migrations.RemoveField(
            model_name="loyalty",
            name="daily_offer_till_time",
        ),
        migrations.CreateModel(
            name="LoyaltyOccurrences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "deleted",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "loyalty_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_occurrences",
                        related_query_name="loyalty_occurrences",
                        to="sharedServices.loyalty",
                    ),
                ),
            ],
        ),
    ]
