# Generated by Django 5.0.9 on 2025-03-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sharedServices",
            "0097_rename_show_daily_offer_loyalty_show_occurrence_offer_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contactlesssessionsdownloadedreceipts",
            name="created_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
