# Generated by Django 5.0.9 on 2025-03-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sharedServices",
            "0098_contactlesssessionsdownloadedreceipts_created_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactlesssessionsdownloadedreceipts",
            name="created_date",
        )
    ]
