# Generated by Django 5.0.9 on 2025-04-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0099_remove_contactlesssessionsdownloadedreceipts_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptheroreceiptsdata',
            name='transaction_id',
            field=models.CharField(max_length=100),
        ),
    ]
