# Generated by Django 5.0.9 on 2025-06-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0066_stations_valeting_site_id'),
        ('sharedServices', '0099_remove_contactlesssessionsdownloadedreceipts_created_date_and_more'),
    ]

    operations = [
    ]
