# Generated by Django 3.2.11 on 2025-07-07 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0100_merge_20250613_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValetingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.BigIntegerField(unique=True)),
                ('machine_name', models.CharField(max_length=255)),
                ('machine_number', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeting_machines', to='sharedServices.stations')),
            ],
            options={
                'db_table': 'valeting_machine',
                'ordering': ['machine_id'],
            },
        ),
    ]
