# Generated by Django 5.0.9 on 2025-04-23 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0100_alter_receiptheroreceiptsdata_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCPICredentialsRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=10, null=True)),
                ('business_details', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('updated_by', models.CharField(max_length=100)),
                ('party_id', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OCPICredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('updated_by', models.CharField(max_length=100)),
                ('x_request_id', models.IntegerField()),
                ('x_correlation_id', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('from_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocpi_credentials_from_role', related_query_name='ocpi_credentials_from_role', to='sharedServices.ocpicredentialsrole')),
                ('to_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocpi_credentials_to_role', related_query_name='ocpi_credentials_to_role', to='sharedServices.ocpicredentialsrole')),
            ],
        ),
    ]
