# Generated by Django 5.0.9 on 2025-07-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0101_valetingmachine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valetingmachine',
            options={},
        ),
        migrations.RemoveField(
            model_name='valetingmachine',
            name='station',
        ),
        migrations.AddField(
            model_name='valetingmachine',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='valetingmachine',
            name='station_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharedServices.stations'),
        ),
        migrations.AddField(
            model_name='valetingmachine',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='valetingmachine',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valetingmachine',
            name='machine_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='valetingmachine',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
