# Generated by Django 5.0.9 on 2025-05-05 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0101_ocpicredentialsrole_ocpicredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffElements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sharedServices_tariffelements',
            },
        ),
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tariff_id', models.CharField(max_length=36)),
                ('country_code', models.CharField(max_length=2)),
                ('party_id', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('AD_HOC_PAYMENT', 'AD_HOC_PAYMENT'), ('PROFILE_CHEAP', 'PROFILE_CHEAP'), ('PROFILE_FAST', 'PROFILE_FAST'), ('PROFILE_GREEN', 'PROFILE_GREEN'), ('REGULAR', 'REGULAR')], max_length=20, null=True)),
                ('tariff_alt_url', models.CharField(blank=True, max_length=512, null=True)),
                ('tariff_alt_text', models.TextField(blank=True, null=True)),
                ('min_price_incl_vat', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_price_incl_vat', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('min_price_excl_vat', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_price_excl_vat', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('energy_mix', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='stationconnector',
            name='tariff_ids',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='TariffComponents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ENERGY', 'ENERGY'), ('FLAT', 'FLAT'), ('PARKING_TIME', 'PARKING_TIME'), ('TIME', 'TIME')], max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('step_size', models.IntegerField(blank=True, null=True)),
                ('element_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_component', related_query_name='tariff_component', to='sharedServices.tariffelements')),
            ],
        ),
        migrations.CreateModel(
            name='TariffRestrictions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(blank=True, max_length=5, null=True)),
                ('end_time', models.CharField(blank=True, max_length=5, null=True)),
                ('start_date', models.CharField(blank=True, max_length=10, null=True)),
                ('end_date', models.CharField(blank=True, max_length=10, null=True)),
                ('min_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('min_current', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_current', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('min_power', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_power', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('min_duration', models.IntegerField(blank=True, null=True)),
                ('max_duration', models.IntegerField(blank=True, null=True)),
                ('reservation', models.BooleanField(blank=True, null=True)),
                ('reservation_expiry', models.BooleanField(blank=True, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=100, null=True)),
                ('element_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_restriction', related_query_name='tariff_restriction', to='sharedServices.tariffelements')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tariffs',
            constraint=models.UniqueConstraint(fields=('country_code', 'party_id', 'tariff_id'), name='unique_tariff_id_party_id_country_code'),
        ),
        migrations.AddField(
            model_name='tariffelements',
            name='tariff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_element', related_query_name='tariff_element', to='sharedServices.tariffs'),
        ),
        migrations.AddConstraint(
            model_name='tariffcomponents',
            constraint=models.UniqueConstraint(fields=('element_id', 'type'), name='unique_type_element_id'),
        ),
        migrations.AddConstraint(
            model_name='tariffrestrictions',
            constraint=models.UniqueConstraint(fields=('element_id', 'day_of_week'), name='unique_day_of_week_element_id'),
        ),
        # migrations.AddConstraint(
        #     model_name='tariffelements',
        #     constraint=models.UniqueConstraint(fields=('tariff_id',), name='unique_tariff_id'),
        # ),
    ]
