# Generated by Django 5.0.9 on 2025-07-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0102_alter_valetingmachine_options_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='stations',
        #     name='valeting_site_id',
        # ),
        migrations.AddField(
            model_name='loyalty',
            name='required_kwh_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyalty',
            name='trigger_sites',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
