# Generated by Django 5.0.9 on 2025-07-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0103_remove_stations_valeting_site_id_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='stations',
        #     name='valeting_site_id',
        # ),
        migrations.AddField(
            model_name='loyalty',
            name='loyalty_trigger_combo',
            field=models.JSONField(blank=True, help_text='JSON for combination triggers', null=True),
        ),
        migrations.AddField(
            model_name='loyalty',
            name='loyalty_trigger_type',
            field=models.CharField(blank=True, choices=[('total_kwh', 'Total kWh'), ('transaction_count', 'Transaction Count'), ('min_kwh_per_transaction', 'Min kWh Per Transaction'), ('total_amount', 'Total Amount'), ('combo', 'Combination')], help_text='Trigger type for Loyalty Offers (separate from Generic Offers)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loyalty',
            name='loyalty_trigger_value',
            field=models.FloatField(blank=True, help_text='Trigger value for single conditions', null=True),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='required_kwh_consumption',
            field=models.FloatField(blank=True, help_text='Required kWh consumption at trigger sites for activation', null=True),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='trigger_sites',
            field=models.JSONField(blank=True, help_text='List of station IDs for custom trigger sites', null=True),
        ),
    ]
