# Generated by Django 5.0.9 on 2025-05-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0103_evse_location_connector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=36)),
                ('country_code', models.CharField(max_length=2)),
                ('party_id', models.CharField(max_length=3)),
                ('type', models.CharField(choices=[('AD_HOC_USER', 'AD_HOC_USER'), ('APP_USER', 'APP_USER'), ('RFID', 'RFID'), ('REMOTE', 'REMOTE'), ('OTHER', 'OTHER')], max_length=20)),
                ('contract_id', models.CharField(max_length=36)),
                ('visual_number', models.CharField(blank=True, max_length=64, null=True)),
                ('issuer', models.CharField(max_length=64)),
                ('valid', models.BooleanField(default=True)),
                ('whitelist', models.CharField(choices=[('ALWAYS', 'ALWAYS'), ('ALLOWED', 'ALLOWED'), ('ALLOWED_OFFLINE', 'ALLOWED_OFFLINE'), ('NEVER', 'NEVER')], max_length=20)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('default_profile_type', models.CharField(blank=True, max_length=20, null=True)),
                ('energy_contract', models.JSONField(null=True)),
                ('last_updated', models.DateTimeField()),
                ('group_id', models.CharField(max_length=36, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='sharedServices.mfguserev')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tokens',
            constraint=models.UniqueConstraint(fields=('uid', 'type'), name='unique_uid_type'),
        ),
    ]
