# Generated by Django 5.0.9 on 2025-05-12 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0104_tokens_tokens_unique_uid_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='type',
            field=models.CharField(choices=[('AD_HOC_USER', 'AD_HOC_USER'), ('APP_USER', 'APP_USER'), ('RFID', 'RFID'), ('OTHER', 'OTHER')], max_length=20),
        ),
        ]
