# Generated by Django 5.0.9 on 2025-08-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0104_remove_stations_valeting_site_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loyalty',
            old_name='required_kwh_consumption',
            new_name='transaction_count_for_costa_kwh_consumption',
        ),
        migrations.RemoveField(
            model_name='loyalty',
            name='loyalty_trigger_combo',
        ),
        migrations.RemoveField(
            model_name='loyalty',
            name='loyalty_trigger_type',
        ),
        migrations.RemoveField(
            model_name='loyalty',
            name='loyalty_trigger_value',
        ),
        # migrations.RemoveField(
        #     model_name='stations',
        #     name='valeting_site_id',
        # ),
    ]
