# Generated by Django 5.0.9 on 2025-08-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0105_rename_required_kwh_consumption_loyalty_transaction_count_for_costa_kwh_consumption_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='stations',
        #     name='valeting_site_id',
        # ),
        migrations.AlterField(
            model_name='loyalty',
            name='terms_and_conditions',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
