# Generated by Django 5.0.9 on 2025-05-27 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0106_ocpicommands_ocpisessions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpicommands',
            name='session_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharedServices.ocpisessions'),
        ),
    ]
