# Generated by Django 5.0.9 on 2025-09-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0106_remove_stations_valeting_site_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='detail_site_check',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
