# Generated by Django 5.0.9 on 2025-05-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0107_ocpicommands_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocpisessions',
            old_name='evse_uid',
            new_name='evse_id',
        ),
    ]
