# Generated by Django 5.0.9 on 2025-06-02 06:25

from django.db import migrations, models


def forwards_func(apps, schema_editor):
        Stations = apps.get_model("sharedServices", "Stations")
        for obj in Stations.objects.all():
            if obj.site_id is not None:
                obj.ocpi_locations = {"DRIIVZ": obj.site_id}
                obj.save()

class Migration(migrations.Migration):


    dependencies = [
        ('sharedServices', '0108_rename_evse_uid_ocpisessions_evse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='ocpi_locations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]