# Generated by Django 5.0.9 on 2025-06-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0110_stationconnector_back_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
