# Generated by Django 5.0.9 on 2025-06-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0111_tokens_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocpisessions',
            name='user_account_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
