# Generated by Django 5.0.9 on 2025-06-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0112_alter_ocpisessions_user_account_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ocpisessions',
            name='unique_location_id_session_id',
        ),
    ]
