# Generated by Django 5.0.9 on 2025-06-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0113_remove_ocpisessions_unique_location_id_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='back_offices',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
