# Generated by Django 5.0.9 on 2025-06-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0066_stations_valeting_site_id'),
        ('sharedServices', '0114_tokens_back_offices'),
    ]

    operations = [
    ]
