# Generated by Django 5.0.9 on 2025-06-22 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0114_tokens_back_offices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='evse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evses', to='sharedServices.evse'),
        ),
        migrations.AlterField(
            model_name='evse',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='sharedServices.location'),
        ),
    ]
