# Generated by Django 5.0.9 on 2025-06-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0115_merge_20250623_1422'),
        ('sharedServices', '0116_alter_connector_evse_id_alter_evse_location_id'),
    ]

    operations = [
    ]
