# Generated by Django 5.0.9 on 2025-06-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0117_merge_20250623_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpisessions',
            name='chargepoint_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocpi_charging_sessions_chargepoints', related_query_name='ocpi_charging_sessions_chargepoints', to='sharedServices.chargepoint'),
        ),
        migrations.AddField(
            model_name='ocpisessions',
            name='station_connector_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocpi_charging_sessions_connectors', related_query_name='ocpi_charging_sessions_connectors', to='sharedServices.stationconnector'),
        ),
        migrations.AddField(
            model_name='ocpisessions',
            name='station_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocpi_station_charging_sessions', related_query_name='ocpi_station_charging_sessions', to='sharedServices.stations'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='is_ocpi_session',
            field=models.BooleanField(default=False),
        ),
    ]
