# Generated by Django 5.0.9 on 2025-06-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0118_ocpisessions_chargepoint_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationconnector',
            name='connector_evse_uid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
