# Generated by Django 5.0.9 on 2025-06-25 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0119_stationconnector_connector_evse_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCPIChargeDetailRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('party_id', models.CharField(max_length=3)),
                ('country_code', models.CharField(max_length=2)),
                ('cdr_id', models.CharField(max_length=39)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('session_id', models.CharField(blank=True, max_length=36, null=True)),
                ('cdr_token', models.TextField()),
                ('auth_method', models.CharField(choices=[('AUTH_REQUEST', 'AUTH_REQUEST'), ('COMMAND', 'COMMAND'), ('WHITELIST', 'WHITELIST')], max_length=20)),
                ('authorization_reference', models.CharField(blank=True, max_length=36, null=True)),
                ('cdr_location', models.TextField()),
                ('meter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('tariffs', models.TextField(blank=True, null=True)),
                ('charging_periods', models.TextField()),
                ('signed_data', models.JSONField(blank=True, null=True)),
                ('total_cost', models.TextField()),
                ('total_fixed_cost', models.TextField(blank=True, null=True)),
                ('total_energy', models.JSONField()),
                ('total_energy_cost', models.TextField(blank=True, null=True)),
                ('total_time', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_time_cost', models.JSONField(blank=True, null=True)),
                ('total_parking_time', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_parking_cost', models.TextField(blank=True, null=True)),
                ('total_reservation_cost', models.TextField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_reference_id', models.CharField(blank=True, max_length=39, null=True)),
                ('credit', models.BooleanField(blank=True, null=True)),
                ('credit_reference_id', models.CharField(blank=True, max_length=39, null=True)),
                ('home_charging_compensation', models.BooleanField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('charging_session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdr_session', related_query_name='cdr_session', to='sharedServices.ocpisessions')),
            ],
        ),
    ]
