# Generated by Django 5.0.9 on 2025-06-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0120_ocpichargedetailrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocpichargedetailrecords',
            name='total_energy',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
