# Generated by Django 5.0.9 on 2025-06-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0120_ocpichargedetailrecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmpecoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=75, null=True, unique=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('fetch_error_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ampeco_data',
            },
        ),
        migrations.AddField(
            model_name='chargepoint',
            name='ampeco_charge_point_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chargepoint',
            name='ampeco_charge_point_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stations',
            name='ampeco_site_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stations',
            name='ampeco_site_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
