# Generated by Django 5.0.9 on 2025-06-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0121_alter_ocpichargedetailrecords_total_energy'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ocpichargedetailrecords',
            constraint=models.UniqueConstraint(fields=('cdr_id', 'country_code', 'party_id'), name='unique_cdr_id_country_code_party_id'),
        ),
    ]
