# Generated by Django 5.0.9 on 2025-06-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0122_ocpichargedetailrecords_unique_cdr_id_country_code_party_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocpicredentials',
            name='x_correlation_id',
        ),
        migrations.RemoveField(
            model_name='ocpicredentials',
            name='x_request_id',
        ),
    ]
