# Generated by Django 5.0.9 on 2025-06-27 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0123_remove_ocpicredentials_x_correlation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCPIModuleDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('credential_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='sharedServices.ocpicredentials')),
            ],
        ),
    ]
