# Generated by Django 5.0.9 on 2025-06-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0124_ocpimoduledetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpimoduledetails',
            name='version',
            field=models.CharField(default='2.2.1', max_length=10),
        ),
    ]
