# Generated by Django 5.0.9 on 2025-06-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0125_ocpimoduledetails_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocpicredentials',
            name='token',
        ),
        migrations.AddField(
            model_name='ocpicredentials',
            name='cpo_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ocpicredentials',
            name='emsp_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
