# Generated by Django 5.0.9 on 2025-06-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0126_remove_ocpicredentials_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpicredentials',
            name='token',
            field=models.CharField(default='1212', max_length=100),
        ),
    ]
