# Generated by Django 5.0.9 on 2025-07-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0127_ocpicredentials_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocpicredentials',
            name='token',
        ),
        migrations.AddField(
            model_name='ocpicredentials',
            name='token_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ocpicredentialsrole',
            name='credential_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
