# Generated by Django 5.0.9 on 2025-07-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0128_remove_ocpicredentials_token_ocpicredentials_token_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocpicredentials',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
