# Generated by Django 5.0.9 on 2025-07-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0100_merge_20250613_1028'),
        ('sharedServices', '0129_alter_ocpicredentials_name'),
    ]

    operations = [
    ]
