# Generated by Django 5.0.9 on 2025-07-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0121_ampecodata_chargepoint_ampeco_charge_point_id_and_more'),
        ('sharedServices', '0130_merge_20250707_1527'),
    ]

    operations = [
    ]
