# Generated by Django 5.0.9 on 2025-07-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0130_merge_20250707_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocpisessions',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('COMPLETED', 'COMPLETED'), ('INVALID', 'INVALID'), ('PENDING', 'PENDING'), ('RESERVATION', 'RESERVATION'), ('AWAITING', 'AWAITING')], max_length=20, null=True),
        ),
    ]
