# Generated by Django 5.0.9 on 2025-07-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0131_alter_ocpisessions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpisessions',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=4, default=20, max_digits=12),
        ),
    ]
