# Generated by Django 5.0.9 on 2025-07-11 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0132_ocpisessions_vat_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedschecklogs',
            name='ocpi_session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_3ds_check_logs_ocpi', related_query_name='user_3ds_check_logs_ocpi', to='sharedServices.ocpisessions'),
        ),
    ]
