# Generated by Django 5.0.9 on 2025-07-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0131_merge_20250709_1459'),
        ('sharedServices', '0133_threedschecklogs_ocpi_session_id'),
    ]

    operations = [
    ]
