# Generated by Django 5.0.9 on 2025-07-12 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0133_threedschecklogs_ocpi_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evse',
            name='location_id',
        ),
        migrations.CreateModel(
            name='OCPIConnector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('connector_id', models.CharField(max_length=36)),
                ('standard', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('power_type', models.CharField(max_length=50)),
                ('max_voltage', models.IntegerField()),
                ('max_amperage', models.IntegerField()),
                ('max_electric_power', models.IntegerField(blank=True, null=True)),
                ('tariff_ids', models.JSONField(blank=True, null=True)),
                ('terms_conditions', models.URLField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField()),
                ('connector_mapping_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_connectors', to='sharedServices.stationconnector')),
            ],
        ),
        migrations.AlterField(
            model_name='ocpisessions',
            name='connector_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharedServices.ocpiconnector'),
        ),
        migrations.CreateModel(
            name='OCPIEVSE',
            fields=[
                ('uid', models.CharField(max_length=36)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evse_id', models.CharField(blank=True, max_length=48, null=True)),
                ('status', models.CharField(max_length=50)),
                ('status_schedule', models.JSONField(blank=True, null=True)),
                ('capabilities', models.JSONField(blank=True, null=True)),
                ('floor_level', models.CharField(blank=True, max_length=4, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_reference', models.CharField(blank=True, max_length=16, null=True)),
                ('directions', models.JSONField(blank=True, null=True)),
                ('parking_restrictions', models.JSONField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
                ('chargepoint_mapping_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chargepoints', to='sharedServices.chargepoint')),
            ],
        ),
        migrations.AddField(
            model_name='ocpiconnector',
            name='evse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocpi_evses', to='sharedServices.ocpievse'),
        ),
        migrations.AlterField(
            model_name='ocpisessions',
            name='evse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharedServices.ocpievse'),
        ),
        migrations.CreateModel(
            name='OCPILocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_id', models.CharField(max_length=36)),
                ('country_code', models.CharField(max_length=2)),
                ('party_id', models.CharField(max_length=3)),
                ('publish', models.BooleanField()),
                ('publish_allowed_to', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=3)),
                ('coordinates', models.JSONField(max_length=50)),
                ('related_locations', models.JSONField(blank=True, null=True)),
                ('parking_type', models.CharField(blank=True, choices=[('ALONG_MOTORWAY', 'ALONG_MOTORWAY'), ('PARKING_GARAGE', 'PARKING_GARAGE'), ('PARKING_LOT', 'PARKING_LOT'), ('ON_DRIVEWAY', 'ON_DRIVEWAY'), ('ON_STREET', 'ON_STREET'), ('UNDERGROUND_GARAGE', 'UNDERGROUND_GARAGE')], max_length=255, null=True)),
                ('time_zone', models.CharField(max_length=255)),
                ('opening_times', models.JSONField(blank=True, null=True)),
                ('charging_when_closed', models.BooleanField(blank=True, null=True)),
                ('directions', models.JSONField(blank=True, null=True)),
                ('operator', models.JSONField(blank=True, null=True)),
                ('suboperator', models.JSONField(blank=True, null=True)),
                ('owner', models.JSONField(blank=True, null=True)),
                ('facilities', models.CharField(blank=True, max_length=1000, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('energy_mix', models.JSONField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
                ('station_mapping_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='sharedServices.stations')),
            ],
        ),
        migrations.AddField(
            model_name='ocpievse',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocpi_locations', to='sharedServices.ocpilocation'),
        ),
        migrations.AlterField(
            model_name='ocpisessions',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='sharedServices.ocpilocation'),
        ),
        migrations.DeleteModel(
            name='Connector',
        ),
        migrations.AddConstraint(
            model_name='ocpiconnector',
            constraint=models.UniqueConstraint(fields=('evse_id', 'connector_id'), name='unique_evse_id_connector_id'),
        ),
        migrations.DeleteModel(
            name='EVSE',
        ),
        migrations.AddConstraint(
            model_name='ocpilocation',
            constraint=models.UniqueConstraint(fields=('country_code', 'party_id', 'location_id'), name='unique_location_id_party_id_country_code'),
        ),
        migrations.AddConstraint(
            model_name='ocpievse',
            constraint=models.UniqueConstraint(fields=('location_id', 'uid'), name='unique_location_id_uid'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
