# Generated by Django 5.0.9 on 2025-07-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0134_merge_20250712_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='ocpi_location_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
