# Generated by Django 5.0.9 on 2025-07-13 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0134_remove_evse_location_id_ocpiconnector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpisessions',
            name='chargepoint_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocpi_charging_sessions_chargepoints', related_query_name='ocpi_charging_sessions_chargepoints', to='sharedServices.chargepoint'),
        ),
        migrations.AddField(
            model_name='ocpisessions',
            name='station_connector_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocpi_charging_sessions_connectors', related_query_name='ocpi_charging_sessions_connectors', to='sharedServices.stationconnector'),
        ),
        migrations.AddField(
            model_name='ocpisessions',
            name='station_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocpi_station_charging_sessions', related_query_name='ocpi_station_charging_sessions', to='sharedServices.stations'),
        ),
        # migrations.AddField(
        #     model_name='ocpisessions',
        #     name='authorization_status',
        #     field=models.CharField(blank=True, max_length=30, null=True),
        # ),
    ]
