# Generated by Django 5.0.9 on 2025-07-13 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0135_ocpisessions_authorization_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidpaymentlogs',
            name='charging_session_ocpi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharedServices.ocpisessions'),
        ),
    ]
