# Generated by Django 5.0.9 on 2025-07-12 08:52

from django.db import migrations
#137

class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0136_rename_tokens_ocpitokens_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tokens',
            new_name='OCPITokens',
        ),
    ]
