# Generated by Django 5.0.9 on 2025-07-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0137_rename_tokens_ocpitokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpisessions',
            name='is_cdr_valid',
            field=models.BooleanField(null=True),
        ),
    ]
