# Generated by Django 5.0.9 on 2025-08-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0135_stations_ocpi_location_id'),
        ('sharedServices', '0138_rename_tokens_ocpitokens_ocpisessions_is_cdr_valid'),
    ]

    operations = [
    ]
