# Generated by Django 5.0.9 on 2025-08-05 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0139_merge_20250805_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpisessions',
            name='cdr_id',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
    ]
