# Generated by Django 5.0.9 on 2025-08-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0140_ocpisessions_cdr_id_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='ocpiconnector',
        #     name='connector_mapping_id',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_connectors', related_query_name='station_connectors', to='sharedServices.stationconnector'),
        # ),
        migrations.AlterField(
            model_name='ocpicredentials',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Initiated', 'Initiated'), ('Failed', 'Failed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ocpisessions',
            name='cdr_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
