# Generated by Django 5.0.9 on 2025-08-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0106_remove_stations_valeting_site_id_and_more'),
        ('sharedServices', '0141_alter_ocpiconnector_connector_mapping_id_and_more'),
    ]

    operations = [
    ]
