# Generated by Django 5.0.9 on 2025-08-18 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0142_merge_20250818_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfguserev',
            name='email',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mfguserev',
            name='sign_in_method',
            field=models.CharField(blank=True, choices=[('Google Sign In', 'Google Sign In'), ('Apple Sign In', 'Apple Sign In'), ('Email Sign In', 'Email Sign In'), ('Guest Sign In', 'Guest Sign In')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mfguserev',
            name='user_email',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        # migrations.AlterField(
        #     model_name='ocpiconnector',
        #     name='connector_mapping_id',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_connectors', related_query_name='station_connectors', to='sharedServices.stationconnector'),
        # ),
    ]
