# Generated by Django 5.0.9 on 2025-08-18 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0143_alter_mfguserev_email_alter_mfguserev_sign_in_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfguserev',
            name='device_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        # migrations.AlterField(
        #     model_name='ocpiconnector',
        #     name='connector_mapping_id',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_connectors', related_query_name='station_connectors', to='sharedServices.stationconnector'),
        # ),
    ]
