# Generated by Django 5.0.9 on 2025-08-24 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0144_mfguserev_device_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlesssessionsdownloadedreceipts',
            name='user_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        # migrations.AlterField(
        #     model_name='ocpiconnector',
        #     name='connector_mapping_id',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_connectors', related_query_name='station_connectors', to='sharedServices.stationconnector'),
        # ),
    ]
