# Generated by Django 5.0.9 on 2025-09-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0107_loyalty_detail_site_check'),
        ('sharedServices', '0145_alter_contactlesssessionsdownloadedreceipts_user_account_number_and_more'),
    ]

    operations = [
    ]
