# Generated by Django 5.0.9 on 2025-08-26 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0145_alter_contactlesssessionsdownloadedreceipts_user_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='is_car_wash',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='loyalty',
            name='visibility',
            field=models.CharField(blank=True, choices=[('Guest Users', 'Guest Users'), ('Registered Users', 'Registered Users'), ('All Users', 'All Users')], max_length=100, null=True),
        ),
    ]
