# Generated by Django 5.0.9 on 2025-09-25 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0146_merge_20250912_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampecodata',
            name='key',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ocpiconnector',
            name='connector_mapping_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_connectors', related_query_name='station_connectors', to='sharedServices.stationconnector'),
        ),
    ]
