# Generated by Django 5.0.9 on 2025-09-10 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0146_loyalty_is_car_wash_loyalty_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='parking_details',
            field=models.CharField(blank=True, max_length=1000, null=True),
        )
    ]
