# Generated by Django 5.0.9 on 2025-09-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0147_alter_ampecodata_key_and_more'),
        ('sharedServices', '0148_stations_parking_details_and_more'),
    ]

    operations = [
    ]
