# Generated by Django 5.0.9 on 2025-09-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0149_merge_20250926_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='display_on_charging_screen',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
