# Generated by Django 5.0.9 on 2025-10-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0150_loyalty_display_on_charging_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='worldline_terminal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
