# Generated by Django 5.0.9 on 2025-10-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedServices', '0151_chargepoint_worldline_terminal_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loyaltyavailableon',
            name='loyaltystationsindexes',
        ),
        migrations.AlterField(
            model_name='mfguserev',
            name='email',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='loyaltyavailableon',
            index=models.Index(condition=models.Q(('deleted', 'No')), fields=['station_id', 'loyalty_id'], name='loyaltystationsindexes'),
        ),
    ]
